# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Docker Registry Purger paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ docker_registry_purger_uid }}"
    group: "{{ docker_registry_purger_gid }}"
  with_items:
    - "{{ docker_registry_purger_base_path }}"
    - "{{ docker_registry_purger_bin_path }}"

- name: Ensure Docker Registry Purger support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ docker_registry_purger_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ docker_registry_purger_uid }}"
    group: "{{ docker_registry_purger_gid }}"
  with_items:
    - env
  register: docker_registry_purger_support_files_result

- name: Ensure Docker Registry Purger bin files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/bin/{{ item }}.j2"
    dest: "{{ docker_registry_purger_bin_path }}/{{ item }}"
    owner: "{{ docker_registry_purger_uid }}"
    group: "{{ docker_registry_purger_gid }}"
    mode: "0750"
  with_items:
    - purge
  register: docker_registry_purger_bin_files_result

- name: Ensure Docker Registry Purger container image is pulled via community.docker.docker_image
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image:
    name: "{{ docker_registry_purger_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ docker_registry_purger_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else docker_registry_purger_container_image_force_pull }}"
  register: docker_registry_purger_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: docker_registry_purger_container_image_pull_result is not failed

- name: Ensure Docker Registry Purger container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ docker_registry_purger_container_image }}"
  register: docker_registry_purger_container_image_pull_result
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: docker_registry_purger_container_image_pull_result is not failed
  changed_when: "'Downloaded newer image' in docker_registry_purger_container_image_pull_result.stdout"

- name: Ensure Docker Registry Purger container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ docker_registry_purger_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: docker_registry_purger_network_creation_result

- name: Ensure Docker Registry Purger container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ docker_registry_purger_container_network }}
  register: docker_registry_purger_network_creation_result
  changed_when: docker_registry_purger_network_creation_result.rc == 0
  failed_when: docker_registry_purger_network_creation_result.rc != 0 and 'already exists' not in docker_registry_purger_network_creation_result.stderr

- name: Ensure Docker Registry Purger systemd services are present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/docker-registry-purger.{{ item }}.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ docker_registry_purger_identifier }}.{{ item }}"
    mode: "0644"
  with_items:
    - service
    - timer
  register: docker_registry_purger_systemd_service_result

- name: Determine whether Docker Registry Purger needs a restart
  ansible.builtin.set_fact:
    docker_registry_purger_restart_necessary: >-
      {{
        docker_registry_purger_support_files_result.changed | default(false)
        or docker_registry_purger_bin_files_result.changed | default(false)
        or docker_registry_purger_systemd_service_result.changed | default(false)
        or docker_registry_purger_container_image_pull_result.changed | default(false)
      }}
